# Generated by Django 4.2 on 2024-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField()),
                ('director_name', models.CharField()),
                ('release_year', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
